version: 2.1

executors:

  basic:
    docker:
      - image: 'funkyfisch/circleci-basic-linting:0.1'

workflows:

  on-pull-request-update:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - prepare
          filters:
            branches:
              ignore: master
      - build:
          requires:
            - lint
          filters:
            branches:
              ignore: master
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: master

  on-master-merge:
    jobs:
      - prepare:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - prepare
          filters:
            branches:
              only: master


jobs:

  prepare:
    executor: basic
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Store list of modified files against master branch
          command: |
            git diff master.."$(git branch --show-current)" --name-only --diff-filter=d > changelist \
              && cat changelist
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    # Add ability to store reports in case of failure
    executor: basic
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run shellcheck on shell scripts, if any
          command: |
            if ! cat changelist | grep "\.\(sh\|ash\|bash\)"
            then
              echo "No shell scripts modified, skipping shellcheck"
            else
              shellcheck $(cat changelist | grep "\.\(sh\|ash\|bash\)")
            fi
      - run:
          name: Run hadolint on modified dockerfiles, if any
          command: |
            if ! cat changelist | grep "\(Dockerfile\|\.dockerfile\)"
            then
              echo "No dockerfiles modified, skipping hadolint"
            else
              echo "Running hadolint"
            fi

  build:
    machine: true
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build modified dockerfiles, if any
          command: |
            if ! cat changelist | grep "\(Dockerfile\|\.dockerfile\)"
            then
              echo "No dockerfiles modified, skipping build"
            else
              docker build \
                --build-arg NODE_MAJOR_VERSION=14 \
                --build-arg NPM_GLOBAL_MODULES="grunt gulp eslint nodemon" \
                -t node-docker-devenv:with-global-addons .
            fi

  publish:
    machine: true
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build and publish new images, if any related content has changed
          command: |
            if cat changelist | grep "\(Dockerfile\|\.dockerfile\)" \
              && cat changelist | grep "\.\(sh\|ash\|bash\)"
            then
              echo "No relevant content changed, skipping build and push"
            else
              docker build \
                --build-arg NODE_MAJOR_VERSION=14 \
                -t "${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}:latest" .
              echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
              docker push "${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}:latest"

            if cat changelist | grep "\.md"
            then
              echo "No documentation was changed, skipping update of docker hub description"
            else
              docker run -v $PWD:/workspace \
                -e DOCKERHUB_USERNAME=$DOCKERHUB_USER \
                -e DOCKERHUB_PASSWORD=$DOCKERHUB_TOKEN \
                -e DOCKERHUB_REPOSITORY="${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}" \
                -e README_FILEPATH='/workspace/README.md' \
                peterevans/dockerhub-description:2
            fi
