version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.2

workflows:

  on-pull-request-update:
    jobs:
      - determine-job-necessity:
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - determine-job-necessity
          filters:
            branches:
              ignore: master
      # - build:
      #     requires:
      #       - lint
      #     filters:
      #       branches:
      #         ignore: master


jobs:

  determine-job-necessity:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: |
          modified_files=$(git diff HEAD..HEAD~1 --name-only --diff-filter=M)
          if [[ "$modified_files" == "README.md" ]]
          then
            circleci-agent step halt
          fi

  lint:
    docker:
      - image:
    steps:
      - checkout
      - shellcheck/install
      - run: |
          shellcheck ./**/*.sh

  # build:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: |
  #         docker build \
  #           --build-arg NODE_MAJOR_VERSION=14 \
  #           --build-arg NPM_GLOBAL_MODULES="grunt gulp eslint nodemon" \
  #           -t node-docker-devenv:latest .
