version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.2
  hadolint: lansweeper/hadolint@x.y.z

workflows:

  on-pull-request-update:
    jobs:
      - determine-job-necessity:
          filters:
            branches:
              ignore: master
      - shellcheck/check:
          requires:
            - determine-job-necessity
          filters:
            branches:
              ignore: master
      - hadolint/lint:
          requires:
            - shellcheck/check
          filters:
            branches:
              ignore: master
      # - build:
      #     requires:
      #       - hadolint/lint:
      #     filters:
      #       branches:
      #         ignore: master


jobs:

  determine-job-necessity:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          modified_files=$(git diff HEAD..HEAD~1 --name-only --diff-filter=M)
          if [[ "$modified_files" == "README.md" ]]
          then
            circleci-agent step halt
          fi


  # build:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: |
  #         docker build \
  #           --build-arg NODE_MAJOR_VERSION=14 \
  #           --build-arg NPM_GLOBAL_MODULES="grunt gulp eslint nodemon" \
  #           -t node-docker-devenv:latest .
